@extends('layouts.app')

@section('head')
<title>For Teacher</title>
<link rel="stylesheet" href="{{asset('assets/css/global.css')}}">
@endsection

@section('content')
<div class="container text-center py-5 my-5">
    <h2 class="fw-700">Teach with Gates and help us</h2>
    <h2 class="fw-700">Shape the workface of the future</h2>
    <p>now is the time!</p>
</div>

<div class="container-fluid my-5">
    <div class="container">
        <div class="row">
            <div class="col d-flex align-items-center justify-content-center">
                <img src="{{asset('assets/images/people.jpg')}}" width="80%" alt="image-assets">
            </div>
            <div class="col">
                <h2 class="mb-3 fw-700">Gates, a new way of building skills</h2>

                <p>
                    Playbook offers high quality learning materials that prepare active generations to evolve in the
                    #WorkforceoftheFuture.
                </p>
                <p>
                    Focused on in-demand skills our learning content is available through in-person sessions and
                    online
                    learning
                </p>
                <p>
                    Our learning materials are taught by experienced teaching partners whose commitment and
                    dedication
                    serve a clear, ambitious goal: <b> successfully accompany our learners in their reskilling and
                        upskilling journey.</b>
                </p>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid bg-mint py-5">
    <div class="container">
        <h2 class="mb-3 fw-700">Introducing On-Demand Workshops</h2>
        <p>
            The On-Demand Workshop is a type of in-class workshop generated by the demand from our learners. On-Demand
            Workshops only happen on the date our learners have selected and if a minimum number of participants is
            reached.
        </p>
        <p>
            Here are several characteristics of an On-Demand Workshop:
        </p>
        <p>
            • Cost effective: it only happens if learners want it to happen, thereby saving time, effort and money for
            the
            teacher;
        </p>
        <p>
            • Revenue effective: as it only happens if a minimum number of learners is reached, a minimum revenue is
            generated for the teacher;
        </p>
        <p>

            • Efficient: only interested learners attend the class, which makes it more beneficial for all parties.
        </p>
        <p>
            By design, On-Demand Workshops are convenient and aim at a single objective: become an innovative learning
            format where learners and teachers win. Lean more here
        </p>
    </div>
</div>

<div class="container-fluid my-5">
    <div class="container">
        <div class="row">
            <div class="col d-flex align-items-center justify-content-center">
                <img src="{{asset('assets/images/work.jpg')}}" width="100%" alt="image-assets">
            </div>
            <div class="col">
                <h2 class="mb-3 fw-700">A Daily Challenge Through Micro Classes</h2>
                <p>
                    Micro Classes are a new way to learn online. Through bite-sized modules, learners can learn every
                    day
                    through a #5MinsDailyChallenge at their own pace.
                </p>
                <p>
                    Bite-sized modules also allow learners to absorb new knowledge faster and shape new skills.
                </p>
                <p>
                    Using a mixed approach (text, video, audio, image, quiz), our Micro Classes evoke the main senses
                    for a
                    better learning experience. Micro Classes are currently offered for free to our learning community.
                </p>
                <p>
                    Interested to share your knowledge on Micro Classes?
                    Learn more here
                </p>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid py-5 mt-5 bg-mint text-center">
    <div class="container">
        <h1 class="fw-700">Count Me In</h1>
        <p>Are you ready to take part in shaping the leaders of the future by sharing your knowledge and wisdom?</p>
        <p class="fw-700">we look forward to having you on board</p>
    </div>
</div>

@endsection
